/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ssi.finalproject.gui;

import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.dao.DaoManager;
import com.j256.ormlite.support.ConnectionSource;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ssi.finalproject.dbaccess.DatabaseManager;
import ssi.finalproject.entities.Item;
import ssi.finalproject.entities.StoLoc;
import ssi.finalproject.gui.models.ItemTableModel;

/**
 *
 * @author GL
 */
public class DemoFunctions extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DemoFunctions.class.getName());

    //Hier ConnectionSource und Daos definieren
    private ConnectionSource connectionSource;
    private Dao<StoLoc, String> stoLocDao;
    private Dao<Item, String> itemDao;

    //Hier das TableModel
    private List<Item> items = new ArrayList<Item>();
    private ItemTableModel tableModel = new ItemTableModel(items);

    /**
     * Creates new form DemoFunctions
     */
    public DemoFunctions() throws SQLException {
        initComponents();
        this.connectionSource = DatabaseManager.getConnection();

        this.stoLocDao = DaoManager.createDao(connectionSource, StoLoc.class);
        this.itemDao = DaoManager.createDao(connectionSource, Item.class);

        //Hier Combobox Vorbefüllen
        List<StoLoc> liste = this.stoLocDao.queryForAll();
        DefaultComboBoxModel<StoLoc> model = new DefaultComboBoxModel<>(new Vector<>(liste));
        cmbStoLocs.setModel(model);

        tblAllItems.setModel(tableModel);
        tblAllItems.setAutoCreateRowSorter(true);
        
        RefreshData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnLoadAndShow = new javax.swing.JButton();
        txtItemName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllItems = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbStoLocs = new javax.swing.JComboBox<>();
        btnDeleteSelected = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("Add an Item");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update an Item");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnLoadAndShow.setText("Load and Show all Items");
        btnLoadAndShow.addActionListener(this::btnLoadAndShowActionPerformed);

        txtItemName.setText("New Item Name");

        tblAllItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAllItems);

        jLabel1.setText("Item Name");

        jLabel2.setText("Storage Location");

        btnDeleteSelected.setText("Delete Selected Item");
        btnDeleteSelected.addActionListener(this::btnDeleteSelectedActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbStoLocs, 0, 193, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoadAndShow)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)
                                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbStoLocs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnLoadAndShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteSelected)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        try {
            Item i1 = new Item();
            i1.setItemId(txtItemName.getText());
            i1.setName(txtItemName.getText());
            i1.setItemLength(10);
            i1.setItemWidth(10);
            i1.setItemHeight(5);
            i1.setPickingStoLoc((StoLoc) cmbStoLocs.getSelectedItem());

            itemDao.create(i1);
            RefreshData();
        } catch (SQLException ex) {
            System.getLogger(DemoFunctions.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(
                    null,
                    "Ein Fehler ist aufgetreten:\n" + ex.getMessage(),
                    "Fehler",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void RefreshData() throws SQLException {
        tableModel.setItems(itemDao.queryForAll());
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        try {
            Item item = this.itemDao.queryForFirst();

            item.setName(item.getName() + "X");

            itemDao.update(item);
            RefreshData();
        } catch (SQLException ex) {
            System.getLogger(DemoFunctions.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(
                    null,
                    "Ein Fehler ist aufgetreten:\n" + ex.getMessage(),
                    "Fehler",
                    JOptionPane.ERROR_MESSAGE
            );
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnLoadAndShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAndShowActionPerformed
        try {

            RefreshData();
        } catch (SQLException ex) {
            System.getLogger(DemoFunctions.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnLoadAndShowActionPerformed

    private void btnDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSelectedActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblAllItems.getSelectedRow();

        if (selectedRow == -1) {

            JOptionPane.showMessageDialog(
                    null,
                    "Bitte zuerst eine Zeile auswählen.",
                    "Hinweis",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            // Wichtig wegen Sortierung!
            int modelRow = tblAllItems.convertRowIndexToModel(selectedRow);

            Item item = this.tableModel.getItemAt(modelRow);

            int result = JOptionPane.showConfirmDialog(
                    null,
                    "Item wirklich löschen?\n" + item.getItemId(),
                    "Bestätigung",
                    JOptionPane.YES_NO_OPTION
            );

            if (result != JOptionPane.YES_OPTION) {
                return;
            }

            itemDao.delete(item);
            RefreshData();

            // Tabelle neu laden
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(
                    null,
                    "Fehler beim Löschen:\n" + ex.getMessage(),
                    "Fehler",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_btnDeleteSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new DemoFunctions().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(DemoFunctions.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteSelected;
    private javax.swing.JButton btnLoadAndShow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<StoLoc> cmbStoLocs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAllItems;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables
}
